### ISSUE TITLE
branch/commit info comes from main working tree, not linked working tree

### ISSUE THREAD

**Issue by seanf** [koraktor/mavanagaiata#100]
See https://github.com/koraktor/mavanagaiata/issues/98#issuecomment-461246233

**Comment by koraktor** [comment]
Apparently, JGit always resolves `HEAD` from the main repository.

A first step to a workaround is setting `HEAD` explicitly:

```
mvn -Dmavanagaiata.head=`git rev-parse --symbolic-full-name HEAD` …
```

This does not help with the dirty state of the working tree, though.

**Comment by koraktor** [comment]
The three patches above should be enough to work around JGit‘s limitations.

Thanks for reporting.

**Comment by koraktor** [comment]
Sorry, I can‘t reproduce this. Can you provide more details?

PS: Are you sure you‘re really using the version build from `master`? Just asking, because I usually don‘t add the `-SNAPSHOT` suffix.

**Comment by seanf** [comment]
I rebuilt mavanagaiata with the version set to 0.9.1s, and when I run that against my repo, the dirty behaviour is correct (for main working tree). I guess it was Maven being Maven. 

But I did notice that the branch name in GitInfo.java is HEAD for the main working tree, instead of the correct branch name (the linked working tree has the correct branch name).

**Comment by koraktor** [comment]
This should be fixed now, too.

**Comment by koraktor** [comment]
@seanf Can you confirm this is fixed now?

**Comment by seanf** [comment]
@koraktor I can't reproduce the problem now, because I've started getting another error, even if I revert to 0.9.1 from Maven Central:

```
[ERROR] Failed to execute goal com.github.koraktor:mavanagaiata:0.9.1:info-class (default-cli) on project bccr-app: Could not get all information from repository: The tags could not be resolved. Object a72b865459c88f96cb520f679b94b6e7b12d8d8f is not a tag. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.koraktor:mavanagaiata:0.9.1:info-class (default-cli) on project bccr-app: Could not get all information from repository
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not get all information from repository
    at com.github.koraktor.mavanagaiata.mojo.AbstractGitMojo.execute (AbstractGitMojo.java:174)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: com.github.koraktor.mavanagaiata.mojo.MavanagaiataMojoException: Could not get all information from repository
    at com.github.koraktor.mavanagaiata.mojo.MavanagaiataMojoException.create (MavanagaiataMojoException.java:32)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.run (InfoClassMojo.java:128)
    at com.github.koraktor.mavanagaiata.mojo.AbstractGitMojo.execute (AbstractGitMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: com.github.koraktor.mavanagaiata.git.GitRepositoryException: The tags could not be resolved.
    at com.github.koraktor.mavanagaiata.git.jgit.JGitRepository.getTags (JGitRepository.java:343)
    at com.github.koraktor.mavanagaiata.git.jgit.JGitRepository.describe (JGitRepository.java:168)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.getValueSource (InfoClassMojo.java:159)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo$ValueSourceFilter.<init> (InfoClassMojo.java:217)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.writeSourceFile (InfoClassMojo.java:208)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.run (InfoClassMojo.java:126)
    at com.github.koraktor.mavanagaiata.mojo.AbstractGitMojo.execute (AbstractGitMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object a72b865459c88f96cb520f679b94b6e7b12d8d8f is not a tag.
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open (WindowCursor.java:173)
    at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes (RevWalk.java:934)
    at org.eclipse.jgit.revwalk.RevTag.parseHeaders (RevTag.java:147)
    at org.eclipse.jgit.revwalk.RevWalk.parseHeaders (RevWalk.java:1047)
    at org.eclipse.jgit.revwalk.RevWalk.peel (RevWalk.java:1084)
    at com.github.koraktor.mavanagaiata.git.jgit.JGitRepository.getTags (JGitRepository.java:336)
    at com.github.koraktor.mavanagaiata.git.jgit.JGitRepository.describe (JGitRepository.java:168)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.getValueSource (InfoClassMojo.java:159)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo$ValueSourceFilter.<init> (InfoClassMojo.java:217)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.writeSourceFile (InfoClassMojo.java:208)
    at com.github.koraktor.mavanagaiata.mojo.InfoClassMojo.run (InfoClassMojo.java:126)
    at com.github.koraktor.mavanagaiata.mojo.AbstractGitMojo.execute (AbstractGitMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

```

**Comment by seanf** [comment]
@koraktor It looks like a72b865459c88f96cb520f679b94b6e7b12d8d8f is a non-annotated tag I created locally.

I deleted the tag, ran the latest code, and it's now getting the branch/commit_abbrev/commit_sha/describe correct. 'dirty' is still wrong of course.

**Comment by koraktor** [comment]
Ok, thanks for testing and thanks for finding another bug.

About the dirty flag: I thought this was already fixed [here](https://github.com/koraktor/mavanagaiata/issues/100#issuecomment-461707040)?

> I rebuilt mavanagaiata with the version set to 0.9.1s, and when I run that against my repo, the dirty behaviour is correct (for main working tree).

**Comment by seanf** [comment]
@koraktor I just meant it was wrong, as expected, in the linked working tree. I think it was fine in the main working tree (I'm not at my work PC right now).

**Comment by seanf** [comment]
@koraktor I just tested again, and the dirty flag is correct in the main working tree. In the linked working tree, it always says dirty, even when both working trees are clean according to `git status`. Everything else looks good in both working trees.

**Comment by koraktor** [comment]
It‘s working fine in my test repositories. Is there anything special, like submodules?

**Comment by seanf** [comment]
No, nothing I can think of. No submodules. I just tried again
with 657cf3df439ade74f1161ac931bc362f41e94b79, and it's the same.
